### ISSUE TITLE
Export All Error

### ISSUE THREAD

**Issue by PabTorre** [awslabs/aws-ai-qna-bot#21] opened 2017-11-07 18:12 UTC
I tried to build a backup by Exporting all 
What I got instead was an empty JSON file contests = {} 

After attempting to use the export filter option all questions were erased from the GUI
and now I'm unable to import or create any questions.

**Comment by tdoyle3** [comment] 2017-11-07 18:20
Have you tried reloading the GUI page?

**Comment by PabTorre** [comment] 2017-11-07 18:41
Yeah reloaded the page and also logged in from another box... same result... 
It seems to be stuck. 

Any idea where the Admin page stores the data for questions?

**Comment by tdoyle3** [comment] 2017-11-07 18:49
All of the data you enter or import is stored in an ElasticSearch instance.

**Comment by JohnCalhoun** [comment] 2017-11-07 19:41
correct, data is stored in AWS ElasticSearch service in an index called "qna-index". from the aws console you can go to elasticsearch, click on the cluster for your bot, go to indices and see the count for how many entries are in elasticsearch. 

So the question is:
is the data there?
did they data not get saved?
or
did the data get deleted somehow?

**Comment by PabTorre** [comment] 2017-11-08 00:59
I nuked the installation and went back to square 1 with a fresh install. :(

**Comment by JohnCalhoun** [comment] 2017-11-08 14:34
Are you still having this issue with the new install?

**Comment by PabTorre** [comment] 2017-11-08 14:42
On the new install I'm able to add questions and export files without problem.

**Comment by JohnCalhoun** [comment] 2017-11-08 18:12
Great to hear! I going to close this issue (since we were not able to reproduce), please re-open if you have the problem again

**Closed by JohnCalhoun** 2017-11-08 18:12 UTC
